# Generated by Django 4.0.5 on 2023-05-13 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='best_time',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='player',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 45, 5, 804490)),
        ),
        migrations.AddField(
            model_name='player',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 45, 5, 804490)),
        ),
    ]
