# Generated by Django 4.0.5 on 2023-05-15 03:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_end_time_alter_player_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 3, 53, 9, 828958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 3, 53, 9, 828958, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_completed', models.BooleanField(default=False)),
                ('level_2_completed', models.BooleanField(default=False)),
                ('level_3_completed', models.BooleanField(default=False)),
                ('level_4_completed', models.BooleanField(default=False)),
                ('level_5_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
