# Generated by Django 4.0.5 on 2023-05-15 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_end_time_alter_player_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='curr_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 4, 40, 51, 957297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 4, 40, 51, 957297, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PlayerProgress',
        ),
    ]
