# Generated by Django 4.0.5 on 2023-05-15 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_curr_level_alter_player_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 10, 12, 2, 68512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 10, 12, 2, 68512, tzinfo=utc)),
        ),
    ]
